### ISSUE TITLE
SPADE 3.0 Roadmap

### ISSUE THREAD

**Issue by javipalanca** [javipalanca/spade#15] opened 2014-10-27 12:59 UTC
I think it's time to plan a new major revision of SPADE. I know there are lots of ideas to improve the platform but I think there are major refactorings that are needed before continuing the development of the platform.
The most important is the most difficult, to change the XMPP library since xmpppy has been discontinued. This affects both the agent library and the xmpp server. In fact, we need to be able to connect to ANY xmpp server (which is not possible nowadays with xmpppy).
I would like to take this moment to also go to Python 3, where we could benefit from asyncio (among others).
I wrote SPADE when I was a python newbie (more than 10 years ago) Both python and me have increased our skills since then, and that should be reflected in the code, with better performance techniques, use of design patterns, clean code, git-flow, etc.

Looking at different python XMPP libraries I think that the most affordable and interesting is SleekXMPP (https://github.com/fritzy/SleekXMPP/) which is compatible with Python 3 and seems to be up-to-date.
Since spade 3 should be compatible with any xmpp server I still like to provide a "toy" python xmpp server that works with the spade installation. Not sure if this is a good idea or we can just include any python server like Wokkel (https://wokkel.ik.nu/) in the requirements.

There will be lots of ideas to discuss (do we want the behaviors agent model again? or any other?, do we need to follow FIPA? etc...) So please start to provide your wishlist for a next-gen Agent Platform.  In the meantime, a new collaborator (MiguelBellver) is going to test SleekXMPP.

Ideas, comments, volunteers...

**Comment by sacsdu** [comment] 2015-03-23 07:21
I don't know much about spade. But I wanted to run this spade with python3.4.3. What I basically tried to do is naive.
1. I ran python's 2to3.py on every python file in the source directory using a script
2. Running
python setup.py installI
I got indentation inconsistency errors in some files. So I manually fixed them.

But now, I'm getting

    F:\Sourcecodes\python\spade\SPADE-2.2.1>python setup.py install
    Could not import spade package!!! No module named 'debug'
    Traceback (most recent call last):
      File "setup.py", line 8, in <module>
        from runspade import __version__
      File "F:\Sourcecodes\python\spade\SPADE-2.2.1\runspade.py", line 19, in <modul
    e>
        from xmppd.xmppd import Server
      File "F:\Sourcecodes\python\spade\SPADE-2.2.1\xmppd\__init__.py", line 1, in <
    module>
        from . import xmppd
      File "F:\Sourcecodes\python\spade\SPADE-2.2.1\xmppd\xmppd.py", line 32, in <mo
    dule>
        from xmpp import *
      File "F:\Sourcecodes\python\spade\SPADE-2.2.1\xmpp\__init__.py", line 29, in <
    module>
        from . import simplexml,protocol,debug,auth,transports,roster,dispatcher,fea
    tures,browser,filetransfer,commands
      File "F:\Sourcecodes\python\spade\SPADE-2.2.1\xmpp\auth.py", line 23, in <modu
    le>
        from .client import PlugIn
      File "F:\Sourcecodes\python\spade\SPADE-2.2.1\xmpp\client.py", line 25, in <mo
    dule>
        import debug
    ImportError: No module named 'debug'

Guys please help me out. Commit is here: https://github.com/sacsdu/spade/commit/91b26fc9817c7010080855b29e2b007069be82ae

**Comment by unimagine** [comment] 2016-02-11 01:24
Hi, I'm very interested in spade as I would like to incorporate it as a component in a personal project. The scope of the project is quite big (predictive demand locations based on finite resources using bayesian methods), and am developing in py3. Are there any current plans to release a py3 based version of Spade? I'm quite excited about the prospect of incorporating an agent-based aspect to my project, but I'm hoping that someday Spade will be released in py3, otherwise I will look to other options. Any idea how things are progressing, if at all?

**Comment by unimagine** [comment] 2016-04-27 23:11
Still keen. I'm tempted to backtrack code to python 2, but as everything in Python is on the cusp at the moment, I feel that would be a mistake. Still holding out for this wonderful piece of software so I can play with some ideas. I know you guys are probably busy doing other life things, so I'll just keep waiting and working on other aspects. Thanks for putting the Spade2 out, if nothing else, I can work with that.

**Comment by Martschink** [comment] 2016-09-14 01:37
I'm curious about how ontologies will work in practice.  I understand the reason for their inclusion and the challenge for which they are offered as a remedy.  At the outset, clearly defining the meaning of every possible word is something of a fool's errand, a fact that keeps lawyers wealthy and miserable.  Also their implementation (required?) is not without burden or risk.  I'm concerned that a hard rule that agents don't hear messages that don't have an exact match of the ontology identifier could actually impair the system.

**Comment by darithleng** [comment] 2017-02-04 04:55
What do you think about improve the SPADE WUI as real-time monitoring on SPADE 3.0?
From agent, it read-time data from the system via RS-232 or CAN-Bus and that data can monitor on WUI from anywhere.

**Comment by mmealling** [comment] 2017-04-30 20:27
The last comment from @javipalanca was from 2014 and the last commit to master was in 2013. General development of XMPP infrastructure essentially stopped a few years earlier than that. Its now 2017 and I'm trying to decide between JADEX, SPADE, and MESA and none are winning. 

I'm seriously thinking of shoving SPADE's BDI library and HTTP transport into MESA and using that. 

Anyone have any advice?

**Comment by mschatten** [comment] 2017-05-07 21:36
Hello Michael,

sorry for the slow response, but it was a busy week. What kind of
applications are you trying to implement? Since MESA is a simulation
platform, and SPADE and JADEX are development platforms... I do not know
much about MESA's internals, so correct me if I'm wrong, but usually
simulation platforms are not suited for development and vice versa.

Regarding further development of SPADE, yeah, mostly the problem is to find
time to work on it... We still use SPADE heavily in our projects and
classes, but no one really has the time to rewrite the XMPP
infrastructure...

All the best,

M.



--
Markus Schatten, PhD
Assistant professor and head of Artificial Intelligence Lab
University of Zagreb
Faculty of Organization and Informatics
Pavlinska 2, 42000 Varazdin, Croatia
http://www.foi.hr/nastavnici/schatten.markus/index.html
http://www.researchgate.net/profile/Markus_Schatten1
http://ai.foi.hr

On Sun, Apr 30, 2017 at 10:27 PM, Michael Mealling <notifications@github.com

**Comment by mmealling** [comment] 2017-06-18 22:05
I'm building an agent based simulation of a cislunar supply chain using concepts from here:
https://engineering.wayne.edu/faculty/govindu-_dissertation.pdf

It is increasingly difficult to find Java developers so I would like to move away from JADEX and its complexities to something like Python. I will be deploying this on AWS so my thought is to replace the XMPP infrastructure with SQS queues.

**Comment by javipalanca** [comment] 2017-06-19 16:26
I had some really bad experience with queue-based protocols (AMQP) and my feelings were that this is not a really good solution for real-time instant messaging.
I'm currently reading about asyncio and having a look at https://github.com/horazont/aioxmpp which looks promising. However, there's still a lack of a server, something like aioxmppd would be really great.

**Comment by Bazmundi** [comment] 2017-10-29 07:52
How about integration of [Profeta](https://github.com/corradosantoro/profeta) as the BDI agent engine?

**Comment by Bazmundi** [comment] 2017-10-29 07:55
Python version of [EIS](https://github.com/eishub/eis) perhaps?

**Comment by Bazmundi** [comment] 2017-11-21 12:18
So, having accidently come across [Pulsar](https://quantmind.github.io/pulsar/) for Python 3, I am now, again, quizzical as to whether SPADE is Agent or Actor oriented.  Sure enough, message passing using FIPA leans one towards Agents but the cognition side ...  is Pulsar plus Profeta all we need?

**Comment by L-Piao** [comment] 2018-08-22 13:19
Dear Javi,
Dear all,

I am a beginner with SPADE and I was confused with its compatibility with Python 3. 

I started with several documentations of SPADE shown below. In such docs, it's mentioned that SPADE supports Python >=3.6.
https://spade-mas.readthedocs.io/en/feature-3.0/
https://media.readthedocs.org/pdf/spade-mas/feature-3.0/spade-mas.pdf

However, when I download and install SPADE (the latest version I've found is 2.3.3) it won't run in Python 3.6 but only in 2.7 environment. Have I understood it correctly, that SPADE 2.3.3 is still based on Python 2, and the new SPADE 3.0.0 is based on Python 3.6 and will appear soon? Thanks for clarifications!

Best Regards,
Piao

**Comment by L-Piao** [comment] 2018-08-23 14:49
Thanks Javi! I downloaded and installed the "develop" branch. A small issue is the "pyasn1".

_removing 'c:\program files (x86)\python36-32\lib\site-packages\pyasn1_modules-0.2.2-py3.6.egg' (and everything under it)
Copying pyasn1_modules-0.2.2-py3.6.egg to c:\program files (x86)\python36-32\lib\site-packages
pyasn1-modules 0.2.2 is already the active version in easy-install.pth

Installed c:\program files (x86)\python36-32\lib\site-packages\pyasn1_modules-0.2.2-py3.6.egg
error: The 'pyasn1' distribution was not found and is required by aioxmpp_

Anyway it's easily solved by "pip install pyasn1". I will report issues while playing with the new SPADE 3.0.0. Thanks for your effort in developing ; )

Best,
Piao

**Comment by javipalanca** [comment] 2018-09-07 17:35
Hi everyone,
I'm happy to announce that SPADE 3 is finally released :)

There is some work that it is still remaining (like transforming the deprecated modules to plugins) but there is at least a functional version.

My next goals are to create as much plugins as needed:
* BDI
* P2P
* Logic
* PubSub
* etc.

So your help and PRs are really welcomed 👍 

Javi

**Comment by filipesaraiva** [comment] 2018-09-07 18:46
@javipalanca  on https://github.com/javipalanca/spade/issues/15#issuecomment-419512587:
> Hi everyone,
> I'm happy to announce that SPADE 3 is finally released :)
> 

Congratulations Javi, it is an amazing checkpoint for Spade development!

> There is some work that it is still remaining (like transforming the deprecated modules to plugins) but there is at least a functional version.
> 
> My next goals are to create as much plugins as needed:

Are you plan create new modules or re-use some existent projects?

**Comment by javipalanca** [comment] 2018-09-10 10:36
Hi,
of course the most desirable thing is not to reinvent the wheel and to use what is already done. 
The extensibility of SPADE 3 is designed to be as easy as posible to add new plugins.
Next big thing I want to do is to create some of them.

**Comment by mschatten** [comment] 2018-09-11 07:38
Congratulations Javi!

I will try to contribute knowledge bases and organizational features as
soon as possible ;-) What would be a desired way to do that, using plug-ins?

All the best,

M.
--
Markus Schatten, PhD
Associate professor and head of Artificial Intelligence Lab
University of Zagreb
Faculty of Organization and Informatics
Pavlinska 2, 42000 Varazdin, Croatia
http://www.foi.hr/nastavnici/schatten.markus/index.html
http://www.researchgate.net/profile/Markus_Schatten1
http://ai.foi.hr

**Comment by javipalanca** [comment] 2018-09-11 10:10
> Congratulations Javi!

Thanks a lot! Glad to read you!

> I will try to contribute knowledge bases and organizational features as
> soon as possible ;-) What would be a desired way to do that, using plug-ins?

Thanks again. Your contributions are so important. The idea is to have a core SPADE as small as possible, and then add the rest of features as plugins.
I'm still thinking about the best way to do it. I've written a *vague* guide where I try to define the ways to contribute plugins to SPADE (https://spade-mas.readthedocs.io/en/latest/extending.html), but I agree that there's a lot of room for improvement.

I'll try ASAP to develop some example plugins in order to validate this plugin mechanisms or not.
Of course, I'm glad to receive contributions and suggestions about this! :)

**Closed** 2019-03-22 18:31 UTC
